
" There options are required by vimwiki.
set nocompatible
filetype plugin on
syntax on

" Load only system and vimwiki's scripts.
set runtimepath=src,$VIMRUNTIME

" Build help tags.
" helptags src/doc

" Use directories within 'test' for storing wiki and html.
let g:vimwiki_list = [{
\	'path': getcwd().'/tests/wiki', 'path_html': getcwd().'/tests/actual',
\	'html_header': '/dev/null', 'html_footer': '/dev/null', 'css_name': ''
\}]

